module SkelGrammar where

-- Haskell module generated by the BNF converter

import AbsGrammar
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transA :: A -> Result
transA x = case x of
  AAdd a1 a2 -> failure x
  AMul a1 a2 -> failure x
  ANum integer -> failure x
  ABrk a -> failure x
transB :: B -> Result
transB x = case x of
  BAdd b1 b2 -> failure x
  B01 b -> failure x
  BMul b1 b2 -> failure x
  B12 b -> failure x
  BNum integer -> failure x
  BBrk b -> failure x

